# Two more things ðŸ˜œ ...

# Methods

- Methods are defined on `type`s
- They have a slightly different syntax than functions <!-- .element: class="fragment" -->
- As part of their signature, they specify what's called a "receiver" <!-- .element: class="fragment" -->

Let's say we have the following `struct`:
```go []
type dog struct {
    name string
}
```

We want to be able to print the name

One method is to have a "separate" function:
```go []
func sayHello(d dog) {
    fmt.Printf("My name is %s", d.name)
}
```
 
But it's the responsibility of `dog` to display its name:
```go []
func (d dog) sayHello() {
    fmt.Printf("My name is %s", d.name)
}
```

How the two methods differ:
```go[1|3|5]
caseysDog := dog{"sorry, I don't know!"}
 
sayHello(caseysDog)
 
caseysDog.sayHello()
```

Using methods, we can implement `interface`s in Go

For example, the following custom type implements the `Reader` interface:
```go [1-3|5,14|6|8-10|12,13]
type myReader struct {
    fileName string
}
 
func (mr myReader) Read(p []byte) (n int, err error) {
    fmt.Printf("reading the contents of %s\n", mr.fileName)
 
    n = -10
    err = errors.New("my error")
    return
 
    // We could also do this
    return -10, errors.New("my error")
}
```

# Error handling

This is where Go is COMPLETELY different than almost all the languages

There's no "exception" in Go ðŸ˜®<br>
Although, the unhandled "exception" is called a `panic`...

So, what happens then?

Every function that _can_ throw an error, returns an `error` as its last return type

Remember the example `interface` we had?
```go []
type Reader interface {
    Read(p []byte) (n int, err error)
}
```
 
It's returning an `error` as its last return type

So, assuming we have two functions<br>
`func1` and `func2` that can throw an<br>
error, an example code flow would be like:
```go []
if err := func1(); err != nil {
    fmt.Println("func1 returned an error; abort!")
    return
}
 
if err := func2(); err != nil {
    fmt.Println("func2 returned an error!")
    // ...
}
```
